# Generated by Django 4.0.3 on 2022-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetclinic', '0002_animal_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='animalId',
            new_name='animal_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='doctorId',
            new_name='doctor_id',
        ),
    ]
