# Generated by Django 4.0.3 on 2022-04-23 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetclinic', '0003_rename_animalid_visit_animal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='animal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vetclinic.animal'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
