# Generated by Django 4.0.3 on 2022-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetclinic', '0007_animal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
