# Generated by Django 4.0.3 on 2022-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetclinic', '0009_animal_customspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='customSpecies',
        ),
        migrations.AddField(
            model_name='species',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
